CREATE TABLE business (
id INT PRIMARY KEY,
city_id INT,
name VARCHAR(255),
latitude DECIMAL(10, 7),
longitude DECIMAL(10, 7),
logo VARCHAR(255),
google_page_url VARCHAR(255),
rating DECIMAL(2, 1),
address TEXT,
email VARCHAR(255),
phone VARCHAR(255),
reviews LONGTEXT,
favourite BOOLEAN,
description TEXT,
program TEXT,
opening_hour VARCHAR(5),
closing_hour VARCHAR(5),
FOREIGN KEY (city_id) REFERENCES cities(id)
);
